2021-03-15 21:56:05,064 INFO    MainThread:12067 [internal.py:wandb_internal():88] W&B internal server running at pid: 12067, started at: 2021-03-15 21:56:05.064313
2021-03-15 21:56:05,065 DEBUG   HandlerThread:12067 [handler.py:handle_request():101] handle_request: run_start
2021-03-15 21:56:05,066 INFO    WriterThread:12067 [datastore.py:open_for_write():77] open: /Users/truongtn/Desktop/Desktop/HocTap/Semester8/Python/YoloV5/yolov5/wandb/offline-run-20210315_215604-36l4qsuj/run-36l4qsuj.wandb
2021-03-15 21:56:06,821 DEBUG   HandlerThread:12067 [meta.py:__init__():34] meta init
2021-03-15 21:56:06,821 DEBUG   HandlerThread:12067 [meta.py:__init__():48] meta init done
2021-03-15 21:56:06,821 DEBUG   HandlerThread:12067 [meta.py:probe():190] probe
2021-03-15 21:56:06,822 DEBUG   HandlerThread:12067 [meta.py:_setup_git():180] setup git
2021-03-15 21:56:06,843 DEBUG   HandlerThread:12067 [meta.py:_setup_git():187] setup git done
2021-03-15 21:56:06,843 DEBUG   HandlerThread:12067 [meta.py:_save_pip():52] save pip
2021-03-15 21:56:06,844 DEBUG   HandlerThread:12067 [meta.py:_save_pip():66] save pip done
2021-03-15 21:56:06,844 DEBUG   HandlerThread:12067 [meta.py:probe():231] probe done
2021-03-15 21:57:10,204 WARNING MainThread:12067 [internal.py:is_dead():343] Internal process exiting, parent pid 12034 disappeared
2021-03-15 21:57:10,205 ERROR   MainThread:12067 [internal.py:wandb_internal():142] Internal process shutdown.
2021-03-15 21:57:11,159 INFO    WriterThread:12067 [datastore.py:close():258] close: /Users/truongtn/Desktop/Desktop/HocTap/Semester8/Python/YoloV5/yolov5/wandb/offline-run-20210315_215604-36l4qsuj/run-36l4qsuj.wandb
2021-03-15 21:57:11,160 INFO    HandlerThread:12067 [handler.py:finish():535] shutting down handler
2021-03-15 21:57:11,210 INFO    SenderThread:12067 [sender.py:finish():872] shutting down sender
2021-03-15 21:57:11,212 INFO    MainThread:12067 [internal.py:handle_exit():78] Internal process exited
